- panc-docs/source/pan-book/pan-book.rst
Fix syntax for foreach example
> Fix syntax in foreach example

- panc/src/test/java/org/quattor/pan/dml/functions/IpToLongTest.java
> Fixes utf-8 error

- panc/src/main/clojure/org/quattor/pan/pan_compiler.clj
- panc/src/main/clojure/org/quattor/pan/settings.clj
> Working initial-data command line option

- panc-docs/source/standard-functions/standard-functions.rst
- panc/src/main/java/org/quattor/pan/dml/functions/Debug.java
- panc/src/main/java/org/quattor/pan/dml/functions/ErrorMessage.java
- panc/src/main/java/org/quattor/pan/dml/functions/Format.java
- panc/src/main/java/org/quattor/pan/dml/functions/Formatter.java
- panc/src/main/java/org/quattor/pan/dml/functions/IpToLong.java
- panc/src/main/java/org/quattor/pan/utils/MessageUtils.java
- panc/src/main/resources/org/quattor/pan/Messages.properties
- panc/src/test/java/org/quattor/pan/dml/functions/DebugTest.java
- panc/src/test/java/org/quattor/pan/dml/functions/ErrorMessageTest.java
- panc/src/test/pan/Functionality/format/format10.pan
- panc/src/test/pan/Functionality/format/format11.pan
- panc/src/test/pan/Functionality/format/format12.pan
- panc/src/test/pan/Functionality/format/format5.pan
- panc/src/test/pan/Functionality/format/format6.pan
- panc/src/test/pan/Functionality/format/format7.pan
- panc/src/test/pan/Functionality/format/format8.pan
- panc/src/test/pan/Functionality/format/format9.pan
- panc/src/test/pan/Functionality/function/function16.pan
- panc/src/test/pan/Functionality/function/function17.pan
- panc/src/test/pan/Functionality/function/function18.pan
> Formatting

- panc/src/main/scripts/panlint/panlint.py
- panc/src/main/scripts/panlint/tests.py
As suggested by @stdweird at some point.
> Panlint: Check profile paths for trailing slashes

- panc/src/main/scripts/panlint/panlint.py
As requested by @stdweird in quattor/template-library-core#150.
> panlint: Include is_nlist() as a bad usage of nlist()

- panc/src/main/scripts/panlint/panlint.py
- panc/src/main/scripts/panlint/tests.py
Fixes #142 
Fixes #143
Also enable use of CodeClimate.
> panlint: support minus sign and simple expressions in squarebrackets

- panc-docs/pom.xml
- panc-maven-archetype/pom.xml
- panc-maven-archetype/src/main/resources/archetype-resources/pom.xml
- panc-maven-plugin/pom.xml
- panc-rpm/pom.xml
- panc/pom.xml
- pom.xml
I disappeared down this rabbit hole trying to fix #148.
> Update maven plugins and disable doclint

- panc/src/main/java/org/quattor/pan/parser/annotation/AnnotationProcessor.java
- panc/src/test/pan/Functionality/annotations/annotation5.pan
> panc: annotations: allow usage of = in description 

- panc/src/main/scripts/panlint/panlint.py
- panc/src/main/scripts/panlint/test_files/test_good_operator.pan
- panc/src/main/scripts/panlint/tests.py
> panlint: refine space after minus sign tests

- panc-docs/source/pan-book/pan-book.rst
- panc/src/main/java/org/quattor/pan/utils/TermFactory.java
- panc/src/test/java/org/quattor/pan/utils/TermTest.java
- panc/src/test/pan/Functionality/path/path2b.pan
>  panc: support generic Term escaping using curly braces 

- panc/src/main/java/org/quattor/pan/utils/TermFactory.java
Replaces `checkStringIndex` caching from PR #171
> panc: TermFactory: cache Term create

- panc/src/main/java/org/quattor/pan/parser/PanParserAstUtils.java
- panc/src/main/java/org/quattor/pan/utils/Path.java
- panc/src/test/java/org/quattor/pan/utils/PathTest.java
- panc/src/test/pan/Functionality/prefix/prefix8.pan
- panc/src/test/pan/Functionality/prefix/prefix9.pan
> panc: allow all relative paths when non-root prefix is used in assignment

- panc/src/main/java/org/quattor/pan/dml/functions/DebugSuppressed.java
- panc/src/test/java/org/quattor/pan/dml/functions/DebugSuppressedTest.java
- panc/src/test/pan/Functionality/debug/debug3.pan
- panc/src/test/pan/Functionality/debug/debug4.pan
> panc: since debug allows for formatted strings, DebugSuppressed should also allow it

- panc/src/main/scripts/panlint/panlint.py
- panc/src/main/scripts/panlint/tests.py
> panlint: allow / as valid path

- panc-docs/source/pan-book/pan-book.rst
- panc/src/main/java/org/quattor/pan/statement/ComputedVariableStatement.java
- panc/src/main/java/org/quattor/pan/statement/ConstantVariableStatement.java
- panc/src/test/pan/Functionality/default/default24.pan
- panc/src/test/pan/Functionality/exists/exists9.pan
- panc/src/test/pan/Functionality/variable/variable16.pan
> panc: null is not a special case for default assigmnent

- panc/src/main/java/org/quattor/pan/type/HashType.java
- panc/src/main/java/org/quattor/pan/type/ListType.java
- panc/src/test/java/org/quattor/pan/JavaCompilerTest.java
- panc/src/test/pan/Functionality/default/default25.pan
- panc/src/test/pan/Functionality/default/default26.pan
- panc/src/test/pan/Functionality/default/default27.pan
- panc/src/test/pan/Functionality/default/default28.pan
> pan: fix default dict/list of custom types

- panc/src/main/java/org/quattor/pan/dml/functions/JsonDecode.java
- panc/src/main/java/org/quattor/pan/dml/functions/JsonEncode.java
These were missed due to order in which the PRs were merged into master.
> Include changes to allow use with latest javacc in JsonEncode/Decode

- panc-docs/source/pan-book/pan-book.rst
simple fix to documentation fixing highlight directive.
> fixing highlight directive

- pan-vim/README.md
- pan-vim/autoload/pancomplete.vim
- pan-vim/syntax/pan.vim
- pan-vim/syntax_checkers/pan/panlint.vim
- Extra highlighting
- Syntastic integration with panlint
Resolves #99
> Some changes to the vim plugin

- panc/src/main/scripts/panlint/panlint.py
- panc/src/main/scripts/panlint/tests.py
Check that they have uppercase names longer than five characters
Add unit tests for checks.
> panlint: Add check for global variable names

- panc-docs/source/pan-book/pan-book.rst
Document why there is no unbind statement in PAN.
Fixes #212.
> PAN Book: Document why there is no unbind

- panc-rpm/pom.xml
- panc/src/main/assembly/bundle.xml
- panc/src/main/scripts/panlint/panlint.py
- panc/src/main/scripts/panlint/tests.py
> Add panlint to rpm

- panc/src/main/scripts/panlint/panlint.py
- panc/src/main/scripts/panlint/tests.py
This is the second part of the work started in #220.
It may be worth reviewing commit-by-commit, I have taken some care to ensure that each commit leaves the code-base in a working state with tests that pass.
Requires #231.
> panlint: Model problems as properties of lines

- .github/workflows/python.yml
- panc/src/main/scripts/panlint/panlint.py
- panc/src/main/scripts/panlint/tests.py
Increases coverage slightly!
Requires #232.
> panlint: Test generation and printing of reports

- panc-docs/source/pan-book/pan-book.rst
- panc-docs/source/standard-functions/standard-functions.rst
- panc/src/main/java/org/quattor/pan/dml/functions/Max.java
- panc/src/main/java/org/quattor/pan/dml/functions/Min.java
- panc/src/main/java/org/quattor/pan/parser/PanParserAstUtils.java
- panc/src/test/java/org/quattor/pan/dml/functions/MaxTest.java
- panc/src/test/java/org/quattor/pan/dml/functions/MinTest.java
- panc/src/test/pan/Functionality/statistical/max1.pan
- panc/src/test/pan/Functionality/statistical/max2.pan
- panc/src/test/pan/Functionality/statistical/max3.pan
- panc/src/test/pan/Functionality/statistical/max4.pan
- panc/src/test/pan/Functionality/statistical/min1.pan
- panc/src/test/pan/Functionality/statistical/min2.pan
- panc/src/test/pan/Functionality/statistical/min3.pan
- panc/src/test/pan/Functionality/statistical/min4.pan
> panc: Implement min and max functions
