quattor/pan

panc-docs/source/commands/commands.rst, panc-docs/source/obtaining/obtain-panc.rst, panc-docs/source/pan-book/pan-book.rst, panc-docs/source/running/running.rst
As this is pan documentation, most of the code snippets are pan!
The PanLexer has been in Pygments since 2.0, so we should make use of it where we can.
=> Documentation: Switch default code highlighter to pan

panc/src/main/scripts/panc
Support for drip (https://github.com/flatland/drip) JVM startup.
Causes significant speedup in the core component unittests (lots of `panc` calls).
=> support drip in panc script

panc/src/main/java/org/quattor/pan/dml/data/ElementUtils.java, panc/src/test/pan/Functionality/undef/undef1.pan, panc/src/test/pan/Functionality/undef/undef2.pan, panc/src/test/pan/Functionality/undef/undef3.pan
The error message should contain the path to the element, not the whole
subtree.
=> Fix error message for undefined values

panc/src/main/java/org/quattor/pan/dml/data/HashResource.java, panc/src/main/java/org/quattor/pan/dml/data/ListResource.java, panc/src/main/java/org/quattor/pan/dml/data/ProtectedHashResource.java, panc/src/main/java/org/quattor/pan/dml/data/ProtectedListResource.java, panc/src/main/java/org/quattor/pan/parser/ASTBaseTypeSpec.java, panc/src/main/java/org/quattor/pan/parser/ASTFunction.java, panc/src/main/java/org/quattor/pan/template/BuildContext.java, panc/src/main/java/org/quattor/pan/template/Context.java, panc/src/main/java/org/quattor/pan/type/FullType.java, panc/src/test/pan/Functionality/global/global6.tpl
This change addresses a concurrency problem, when two distinct threads
processing the same non-object template ended up modifying the same
HashResource object simultaneously, leading to TreeMap corruption, which
manifested itself as NullPointerException or compiler hang. The trigger
was a foreach() loop over a protected hash, which did not propagate
the protection down to the hash values; the stack trace leading for this
situation was:
[panc] org.quattor.pan.dml.data.HashResource.put(HashResource.java:172)
[panc] org.quattor.pan.dml.data.Resource.rput(Resource.java:131)
[panc] org.quattor.pan.template.BuildContext.setLocalVariable(BuildContext.java:1298)
[panc] org.quattor.pan.dml.operators.SetValue.execute(SetValue.java:170)
[panc] …
=> Resource protection should be deep, not shallow

panc/src/main/scripts/panlint/panlint.py, panc/src/main/scripts/panlint/test_files/mvn_template_first_line.pan, panc/src/main/scripts/panlint/tests.py
* Report extra white-space after semicolons.
* Add option to allow Maven templates to be used for the first line (allows tests to pass for quattor/configuration-modules-core#1031).
=> Panlint: Additional rules

panc/src/main/scripts/panlint/panlint.py, panc/src/main/scripts/panlint/tests.py
This uncovered a bug when multiple instances of a single error are present on the same line, which ignored all but the first match.
=> Panlint: Add unit tests for whitespace after semicolons

panc/src/main/scripts/panlint/panlint.py
This should hopefully fix #137.
=> Only use Unicode if stdout claims to support UTF-8

panc/src/main/scripts/panlint/panlint.py
Typically, one can use xargs to pass the PATHs of changed files. On systems with non-GNU xargs, there is no way to cancel the command when an empty list is provided (-r is a GNU-only extension).
This PR addresses this, allowing the command to run without files to check.
=> Allow empty paths, making life easier on BSD-type systems

panc/src/main/scripts/panlint/panlint.py, panc/src/main/scripts/panlint/tests.py
* Don't helpfully strip trailing white-space before checking for it.
* Don't crash if there are no characters before or after an operator.
=> Panlint: fix whitespace checks

panc/pom.xml
To workaround the failing jenkins unittests of the master branch, eg
```
[xUnit] [INFO] - Starting to record.
[xUnit] [INFO] - Processing JUnit
[xUnit] [INFO] - [JUnit] - 154 test report file(s) were found with the pattern '*/target/surefire-reports/*xml' relative to '/var/lib/jenkins/jobs/panc/workspace' for the testing framework 'JUnit'.
[xUnit] [ERROR] - The result file '/var/lib/jenkins/jobs/panc/workspace/panc/target/surefire-reports/TEST-org.quattor.ant.DebugPatternsTest.xml' for the metric 'JUnit' is not valid. The result file has been skipped.
[xUnit] [INFO] - Failing BUILD because 'set build failed if errors' option is activated.
[xUnit] [INFO] - There are errors when processing test results.
[xUnit] [INFO] - Skipping tests recording.
[xUnit] [INFO] - Stop build.
```
=> panc: set minimal surefire plugin version to pass JUnit

panc/src/main/scripts/panlint/panlint.py, panc/src/main/scripts/panlint/tests.py
* Add unit tests to ensure that this is detected correctly.
* Update unit tests that would trigger this unintentionally.
* Fix some pep8 issues.
=> Panlint: Mark components referred to in prefix statements as used

panc/src/main/scripts/panlint/panlint.py
Some testing frameworks interpret tools exiting with a non-zero code as a
failure of the tool rather than the tests it performs, adding this option
allows panlint to be used with these tools. (e.g. arcanist).
=> panlint: Add option to exit cleanly even if problems are found

panc/src/main/java/org/quattor/pan/parser/PanParserAnnotationUtils.java
Fixes #132 
```pan
object template a;
type mytype = {
@{abc}
'a' : long = 1
'b' ? string = 'b'
'c' ? boolean
};
"/a" = 1;
```
gives annotation
```xml
<?xml version="1.0" encoding="UTF-8"?><template xmlns="http://quattor.org/pan/annotations" name="a" source-range="1.1-1.18" type="OBJECT">
<type name="mytype" source-range="3.1-8.2">
<basetype source-range="3.15-8.1" extensible="false">
<field name="a" source-range="5.5-5.7" required="true">
<desc>abc</desc>
<basetype name="long" source-range="5.11-5.14" extensible="false"/>
<default source-range="5.18-5.18" text="1"/>
</field>
<field name="b" source-range="6.5-6.7" required="false">
<basetype name="string" source-range="6.11-6.16" extensible="false"/>
<default source-range="6.20-6.22" text="b"/>
</field>
<field name="c" …
```
=> annotations: add default to annotation for attribute type with a default

panc-docs/source/pan-book/pan-book.rst, panc/src/main/java/org/quattor/pan/utils/MessageUtils.java, panc/src/main/java/org/quattor/pan/utils/TermFactory.java, panc/src/main/resources/org/quattor/pan/Messages.properties, panc/src/test/java/org/quattor/pan/utils/PathTest.java, panc/src/test/java/org/quattor/pan/utils/TermTest.java, panc/src/test/pan/Functionality/path/path14.pan, panc/src/test/pan/Functionality/path/path6.pan
Fixes #156
This is backwards incompatible because eg hex and/or octal notations cannot be used anymore.
=> panc: only allow digit-only string as candidate list index (and allow anything else as dict key)

panc-docs/source/standard-functions/standard-functions.rst, panc/src/main/java/org/quattor/pan/dml/functions/Value.java, panc/src/test/pan/Functionality/value/value2.pan, panc/src/test/pan/Functionality/value/value3.pan, panc/src/test/pan/Functionality/value/value4.pan, panc/src/test/pan/Functionality/value/value5.pan, panc/src/test/pan/Functionality/value/value6.pan, panc/src/test/pan/Functionality/value/value7.pan, panc/src/test/pan/Functionality/value/value8.pan, panc/src/test/pan/Functionality/value/value9.pan
=> pan: support default/fallback value for built-in function value()

panc/src/main/java/org/quattor/pan/repository/FileSystemSourceRepository.java, panc/src/main/java/org/quattor/pan/repository/FileSystemSourceRepositoryImpl.java
Avoid expensive filesystem lookups from lookupSource, mainly in case of large number of include directories and/or loadpaths
=> panc: FileSystemSourceRepository: cache retrievePanSource

panc/src/main/scripts/panlint/panlint.py, panc/src/main/scripts/panlint/tests.py
Modelling lines (and eventually other parts of the checks) as objects makes it much simpler to keep related information together as it moves around and opens up the possibility for decoupling the analysis and presentation layers.
This is part one of five major re-factoring steps that were undertaken at RAL, it has taken some time to clean-up the changes into something that can be reviewed in a sane way.
Requires #219.
=> Panlint: Model lines as objects

.travis.yml, panc/src/main/scripts/panlint/panlint.py, panc/src/main/scripts/panlint/tests.py
As Fedora 31 lets python point to python 3, it broke panlint. This PR makes sure that panlint works with both python 2 and 3.
=> Fix panlint for python 3

panc-docs/source/pan-book/pan-book.rst
I noticed a formatting error in the Resources section. Replace the digit 0 with the text zeros to eliminate it.
=> pan-book: correct formatting error

panc/src/main/scripts/panlint/panlint.py, panc/src/main/scripts/panlint/test_files/test_good_before_first_line.pan, panc/src/main/scripts/panlint/tests.py
This fixes a regression introduced when lines became objects and the references in this line were not updated correctly.
Fixes #230 and I believe it therefore fixes #224.
=> panlint: Don't lint blank lines

panc/src/main/scripts/panlint/panlint.py, panc/src/main/scripts/panlint/tests.py
This should cut out much of the rubbish flagged against test files etc. and obviate some of the need for #225.
=> panlint: Don't require component source files to include component config

panc/src/main/scripts/panlint/panlint.py, panc/src/main/scripts/panlint/test_files/test_good_structure.pan
I've changed the order of the 'if' statements. If the operator is within a string, we just skip it.
Fixes #240
=> panlint: Skip checks of operator if within a string

.github/workflows/python.yml
This allows the tests to run on forks too.
As requested by @wpoely86.
=> github/workflows: Remove branch restriction

panc/src/main/scripts/panlint/panlint.py, panc/src/main/scripts/panlint/tests.py
Both `error` and `debug` have built in formatting.
=> panlint: Flag redundant use of format function within error or debug calls

panc/pom.xml
The `@expect` lines in the Pan unit tests contain very large xpath expressions which cannot be used with the default of 10.
Resolves #259.
=> Increase the number of operators an XPath expression can contain during tests

panc/src/main/scripts/panlint/panlint.py
Panlint will not issue errors about the missing include for any component in the whitelist.
=> panlint: Add option to ignore missing inclusion of components/config

panc/src/main/scripts/panlint/panlint.py, panc/src/main/scripts/panlint/tests.py
These are often required to be very long due to binds being made deep into the profile path. There is is no good way to refactor these, so they should not be flagged.
=> panlint: Ignore length of bind lines

panc/src/main/scripts/panlint/panlint.py, panc/src/main/scripts/panlint/tests.py
i.e. one feature including a template from another
=> panlint: Add check for features being included from outside their tree

panc/src/main/scripts/panlint/panlint.py
This is contrary to the documentation, but accepted by the compiler.
=> panlint: Allow whitespace between annotation name and body

panc/src/main/scripts/panlint/panlint.py
Only print the summary if the option is set.
=> panlint: Provide print summary option

panc/src/main/scripts/panlint/panlint.py, panc/src/main/scripts/panlint/tests.py
- Give messages a unique ID to allow them to be referred to without breaking if the message text changes.
- Give messages a severity to allow a threshold to be set in future.
This is one part of the work that was done at RAL back in 2018 to allow tests to be 
suppressed with magic comments, cherry-picked out into a manageable chunk.
=> panlint: Model messages as objects with a severity

panc/src/main/scripts/panlint/tests.py
=> panlint: Unittest fixes

panc-docs/.readthedocs.yaml, panc-docs/pom.xml, panc-docs/requirements.txt, panc-docs/source/conf.py, panc-maven-archetype/pom.xml, panc-maven-plugin/pom.xml, panc-rpm/pom.xml, panc/pom.xml, pom.xml
The `pan-10.8` tag already points at these changes and the resulting documentation is live at:
https://quattor-pan.readthedocs.io/en/pan-10.8/
=> Updates to allow build of docs for pan 10.8

panc/src/main/java/org/quattor/pan/dml/functions/Matches.java, panc/src/test/java/org/quattor/pan/dml/functions/MatchesTest.java, panc/src/test/pan/Functionality/regexp/regexp5.pan
Rather than an ugly stack trace.
This is basically the same fix made to match in 5fb981cd1d3d367df122a1ad3199359141ae4b64
Resolves #273.
=> panc: Throw a nice error when matches is called with a single argument
